name: Deploy creater Dashboard

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_DEV_USERNAME: ${{ secrets.DATABASE_DEV_USERNAME }}
      DATABASE_DEV_PASSWORD: ${{ secrets.DATABASE_DEV_PASSWORD }}
      DATABASE_PROD_USERNAME: ${{ secrets.DATABASE_PROD_USERNAME }}
      DATABASE_PROD_PASSWORD: ${{ secrets.DATABASE_PROD_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.OWNER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker compose build
        docker compose push

    - name: Deploy to Portainer
      run : |
        echo "Deploying to Portainer"