name: Deploy creater Dashboard

on:
  push:
    branches: [ "main", "feature/CI" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_DEV_USERNAME: ${{ secrets.DATABASE_DEV_USERNAME }}
      DATABASE_DEV_PASSWORD: ${{ secrets.DATABASE_DEV_PASSWORD }}
      DATABASE_PROD_USERNAME: ${{ secrets.DATABASE_PROD_USERNAME }}
      DATABASE_PROD_PASSWORD: ${{ secrets.DATABASE_PROD_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.OWNER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker compose build
        docker compose push

    - name: Deploy stack to Portainer
      uses: carlrygart/portainer-stack-deploy@v1
      with:
        portainer-host: https://portainer.benevolo.de
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        stack-name: 'benevolo-creater-dashboard'
        stack-definition: 'docker-compose.yml'
        image: ghcr.io/thi24/benevolo.creator.dashboard:${GITHUB_RUN_ID}
